### ISSUE TITLE
multiprocessing not able to spawn worker processes

### ISSUE THREAD

**Issue by hhibiscuits** [TeamTernate/infinite-music-discs#100]
Everything works great up until I hit generate. My computer gives me a bizarre 'this app can't run on your PC' pop up that I need to click multiple times until the screen fades back to normal. Then, the app tells me that it had trouble converting the files to .ogg, but on my second try the files were already .ogg and mono to limit conversion issues (first try was just .mp3 and stereo). I used [this website](https://audio.online-convert.com/convert-to-ogg) to convert the songs (from mp3 to .ogg and stereo to mono) after downloading them through [this Spotify convertor](https://spotifydown.com/). No matter what settings I have selected (ie. mc ver, jukebox conv), I get the exact same error. Here's some more info:

v1.6 (current newest version)
Windows 10
had a precarious time allowing it through my anti malware service in case that is still affecting things (ended up disabling it temporarily)

Tried to keep it concise but let me know if you need more info :) Thanks so much for sharing your awesome work with the community!

**Comment by bradytheinventor** [comment]
When it comes to bug reporting, there's no such thing as too much detail!

However in this case I do know what the problem is. The app uses a Python module called multiprocessing to spawn several sub-processes that let it convert multiple files at once to save time. Apparently your computer blocks the sub processes from launching, which breaks the app. The app tries to process every file you give it to prevent problems down the line, and there's not currently a way to bypass the processing.

What anti malware service are you using? What happens if you click the generate button a second time after dismissing the pop up warnings?

I will try to fix this or add a workaround; in the meantime you could try using an older version of the app.

**Comment by bradytheinventor** [comment]
I added a setting to process the tracks one by one, which will let you avoid the problem you're facing. It's available in the latest version which was just released.
