### ISSUE TITLE
[Feature Request] Disc image creator

### ISSUE THREAD

**Issue by TimyIsCool** [TeamTernate/infinite-music-discs#106]
Hi, So this is a very quality of life request but a built in way to edit the music disk image would be awesome, I can't figure out how to get the perfect pixels to create my own music disk

**Comment by bradytheinventor** [comment]
Making a built-in image editor is unfortunately pretty difficult. I briefly considered it at the beginning but decided against it because it was going to be so hard.

If you need an image editor that works well with Minecraft textures, GIMP and paint.NET are both popular. Personally, I use GIMP to edit pre-existing music disc textures (like the example disc texture that gets distributed with the app) and export them with a different name.
