### ISSUE TITLE
"Unknown function" when trying to /give discs.

### ISSUE THREAD

**Issue by gracemotley** [TeamTernate/infinite-music-discs#25]
After uploading both rp and dp packs to their respective folders as .zips and unzipped, reloading datapacks in-game results in the message "Custom Music Discs v1.9 by link2_thepast" regardless of what the actual pack name is. /give commands for both individual discs and for all discs result in "Unknown function <command>". Same result in singleplayer and multiplayer in which the datapack is uploaded to the server.
![datapacks active](https://user-images.githubusercontent.com/97651909/149262282-cbd35f95-88a9-45ef-8be0-942f25345bf4.PNG)
![resource packs selected](https://user-images.githubusercontent.com/97651909/149262285-ebcd4899-bd70-4d10-9115-09e69ae80707.PNG)
![unknown function](https://user-images.githubusercontent.com/97651909/149262287-f6942820-6c70-408e-a31f-3ba8701783f7.PNG)

**Comment by bradytheinventor** [comment]
Thanks for filing an issue. The title will always be "Custom Music Discs"; the name setting is mostly for internal use to avoid namespace collisions.

Looks like the datapack is referring to `custom_music_discs` functions, which of course don't exist because you changed the name. Will be fixed in the next release, for now just leave the datapack name setting as the default `custom_music_discs`.

**Comment by gracemotley** [comment]
Update: I tried running the functions on Vanilla instead of my Forge client, which worked. I then reinstalled Forge and tried it again and it worked. I think the issue was the name of the pack -- when I would it tab before, it wouldn't prompt anything at all, but when I did it after, it had the disc commands available.
