### ISSUE TITLE
Mod compatibility with Sophisticated Backpacks

### ISSUE THREAD

**Issue by gracemotley** [TeamTernate/infinite-music-discs#26]
The mod "Sophisticated Backpacks" has an upgrade system where you can add things to your backpack like a magnet (picks up nearby items and places them in the backpack automatically) or a portable jukebox (can play a music disc wherever the player walks). Tested it with custom discs, and it just plays 13 no matter what disc you put in (unless it's a vanilla disc, then it works as expected). I checked the config for the backpacks mod to see if I could change what IDs the backpack accepts as "discs" but there was nothing there, so I'm not sure if it's possible.

**Comment by bradytheinventor** [comment]
Unfortunately, vanilla Minecraft doesn't have a mechanism for datapacks/resourcepacks to add new custom items. The only option is to reskin existing items and override the skinned item's behavior with commands. That's why you're hearing 11 from all custom discs; internally they're considered disc 11, and the mod has no way to detect the custom behavior.

Since you're using Forge anyway, you might be able to use a mod like [MCDJ](https://www.curseforge.com/minecraft/mc-mods/mcdj) to do what you want.
