### ISSUE TITLE
Music Desktop Client frozen when generating pack

### ISSUE THREAD

**Issue by P1neAppl** [TeamTernate/infinite-music-discs#31]
I've let it run overnight, starting the music generation at 9:30. The Bar sets to one specific spot and just sits there. I'm not entirely sure if I've missed anything in the download or it's really just a bug overall

![image_2022-04-23_095035064](https://user-images.githubusercontent.com/104263565/164907668-22328114-1a09-4de3-bd7c-789c02a22cae.png)

Here's the visual problem example image, hope it works well. Let me know if you need better, and I'll try my best

**Comment by bradytheinventor** [comment]
I've seen this happen with mp3 files downloaded from free converter websites (youtube-to-mp3, etc). This should be fixed in the next update; for now you can convert your tracks to .ogg ([https://audio.online-convert.com/convert-to-ogg](https://audio.online-convert.com/convert-to-ogg)) before running them through the tool.

Pack generation should take seconds/minutes for the number of files you've selected.

**Comment by P1neAppl** [comment]
@bradytheinventor thanks for that, I'll use the .ogg converter and see if that helps.

**Comment by bradytheinventor** [comment]
Should be fixed by c6f0dd1, will do more testing before the next release.

**Comment by bradytheinventor** [comment]
I haven't seen this bug anymore in testing, so I think it's fixed.
