### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by jurama128** [TeamTernate/infinite-music-discs#49]
Hi this project is amazing but i have one problem. When you use normal music disc and go away you stop hearing it but it doesnt work with custom discs.

**Comment by Daltaxy** [comment]
same for me in 1.19.2.

**Comment by bradytheinventor** [comment]
It's because of how Minecraft's sound engine works: stereo sounds play "in your head" like you noticed, and mono sounds play "in the world" from a location. Most music is stereo, so it plays in your head.

There's an option in the app to convert your songs to mono so they play from the jukebox. It's in the Settings tab.

**Comment by Daltaxy** [comment]
> It's because of how Minecraft's sound engine works: stereo sounds play "in your head" like you noticed, and mono sounds play "in the world" from a location. Most music is stereo, so it plays in your head.
> 
> There's an option in the app to convert your songs to mono so they play from the jukebox. It's in the Settings tab.

I didn't know that was the cause, thank you :)
