### ISSUE TITLE
found the max amount of songs you can add

### ISSUE THREAD

**Issue by markiegaming** [TeamTernate/infinite-music-discs#5]
it is some where between 30 and 39 after that it just plays music disc 11

**Comment by markiegaming** [comment]
to be precise it is 35

**Comment by bradytheinventor** [comment]
I generated a stress-test datapack with 158 discs and all of them played fine. You must have something else going wrong.

**Comment by Skyball2000** [comment]
The problem is with the pack file size:
```
[STDERR]: java.io.IOException: Filesize is bigger than maximum allowed (file is 6.0, limit is 104857600)
[STDERR]: 	at agw.a(SourceFile:170)
[STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```
You must have tested it with small files only. Is there a way to increase this setting?

**Comment by bradytheinventor** [comment]
> You must have tested it with small files only. Is there a way to increase this setting?

Maybe, what do you consider "small"? My stress-test pack is 1GB, with an average file size of 7MB. I just added a 49MB white noise track to the pack with no apparent issues.

Maybe Minecraft is running out of memory. You could try allocating more memory to the game using JVM arguments in the launcher. There are lots of guides online for how to do it. 2 or 3 GB is probably enough.

**Comment by Skyball2000** [comment]
Okay, that's weird. Mine only has `115MB`.
Chaging the memory to `4G` didn't change anything, the log still says `Limit is 104857600B`, around `100MB`.

Okay I just realized what the problem is while writing this. You're testing this as a singleplayer resource pack, aren't you? Singleplayer resource packs don't limit the file size.
But server resource packs do. If I set the `resource-pack` option in the `server.properties` file to my resource pack that is larger than `100MB`, the Minecraft client refuses to download the file as it considers it to be too large.

Well, then I'll have to limit myself to `100MB` for my server.

Thank you so much for creating this tool by the way! It's so cool!

**Comment by bradytheinventor** [comment]
Ah, that makes sense. I do test in singleplayer, or with a `localhost` server. If your playerbase is small you could distribute the pack through a side channel like Discord.

Glad you like the tool! It fills a need a lot of players have, I think.

**Comment by Skyball2000** [comment]
Sorry for reviving this, but there is some good News about this:  
Mojang just released an update where they increase the max server resourcepack size from 100 to 250mb!
https://www.minecraft.net/de-de/article/minecraft-1-18-release-candidate-1
