### ISSUE TITLE
Compatibility with Sophisticated Backpacks

### ISSUE THREAD

**Issue by Daltaxy** [TeamTernate/infinite-music-discs#50]
Hello.
1.19.2, latest forge version.
Sophisticated Backpacks has an addon that allows one to play music discs with their backpack.
When I try to play the custom disk on there, it plays a minecraft music disk. Any fix planned ?

**Comment by bradytheinventor** [comment]
No, unfortunately that's not possible due to how the datapack works. Vanilla Minecraft doesn't have a way to add new items to the game, so the custom discs are actually disc "11" retextured with some datapack code to make them play the custom songs. I don't see a way to be compatible with both mods and vanilla.

**Comment by Daltaxy** [comment]
that makes sense, thank you.
