### ISSUE TITLE
Aternos Server Compatibility

### ISSUE THREAD

**Issue by RetroLemonade** [TeamTernate/infinite-music-discs#56]
Won't work for Aternos servers

**Comment by GameDokter51** [comment]
Is the issue with the datapack or resource pack? (i.e. do the functions and whatnot work but not the sounds and textures, or do the sounds and textures work but not the functions and actual ability to use the discs in a jukebox)
I planed on using this on an Aternos server so that would be good to know.

**Comment by bradytheinventor** [comment]
I generated a pack with 26 discs and uploaded it to an Aternos server and it worked. I used v1.5 of the app, with the "generate packs as zip" and "play tracks from the jukebox" settings enabled. I used the Aternos web UI to create a new server, added the datapack into my `world/datapacks` folder from the Files menu, and uploaded the resourcepack through the Options menu. After restarting the server, everything worked perfectly.

If you're having issues with Aternos you may be uploading the files incorrectly.
