### ISSUE TITLE
After some seconds disc 11 starts playing trough my custom disc.

### ISSUE THREAD

**Issue by GurbePieter** [TeamTernate/infinite-music-discs#73]
Yo, i have some problems with your product. When i put my music disc in, it works normally. But after some seconds disc 11 starts playing trough it. Do u know a fix?

**Comment by bradytheinventor** [comment]
I haven't seen that happen before. How many seconds does it take before 11 starts playing? Are you playing on a server or a slow computer? This could be caused by lag.

How many music discs did you add? Do you have any other datapacks installed? How are you playing the music discs (by hand or hopper)? Any information you can give me will be helpful for debugging. Thanks!

**Comment by GurbePieter** [comment]
With vanilla refresh datapack. The setting loop jukeboxes was the issue! Sorry😅
