### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by GudanCraft** [TeamTernate/infinite-music-discs#84]
I have multiple issues that affect my usage of these resource / datapacks. I play Minecraft currently on version 1.20 on the legitimate Java application / I play on Lunar Client which means i am not playing cracked MC. My PC is not even near the best, relatively low-end but I can still solidly run MC enough well to know something doesn't work.

DISC APPLICATION ISSUES:

- 1: **ALL of my music are already .ogg and the app still says that it couldn't convert some of the files to .ogg format.** What is the need for this if all of them are already .ogg

- 2: When using the app i place all of the songs and the disc images i made (all adhere to the 16x16 format) but still some do not load in the app when generating a pack.

IN-GAME ISSUES:

- 1 Both in singleplayer worlds and in my personal server i am an OP at the discs are not able to load properly. By that i mean that **all of the discs with names of my songs (for example Sehnsucht - Rammstein) have the icon of Disc 11 and they produce no music at all, fully mute when on jukebox.** And yes, my music and sound settings are turned, i didn't accidentally lower the volume or something.

- 2 When i tried to get discs by having skeletons kill creepers, **all I got were default disc 11's but their name was the name of my own songs.**

![2023-07-05_16 32 29](https://github.com/TeamTernate/infinite-music-discs/assets/138683147/07ff4d0a-dc6c-4c09-82d6-fb1d61ffa986)

- 3: I planned to use this datapack as a general pack to buff the experience of my friends on my server (**in Aternos**) so that all of us could gain the discs and collect them. Problem is that even though i placed the datapack in the correct folder for the server, none of the discs appear in the server itself.

- 4: I placed the zipped RP file in my .minecraft folder for resource packs and i cannot find it in the RP settings in minecraft:
![image](https://github.com/TeamTernate/infinite-music-discs/assets/138683147/b8669172-ee5e-4ce0-9c5d-f4497ccfc33b)

     - I loaded the server and the datapacks on the Aternos website AND loaded the same resource pack in my minecraft (I use Lunar   Client) and used the commands mentioned in the video for this process (https://www.youtube.com/watch?v=zDXSKYvJXmg), but instead of getting a custom disc like the person in the video, i just get the general disc 11 which has "2 tags" mentioned.

**Comment by bradytheinventor** [comment]
Thanks for the detailed post! Hopefully I can answer your questions.

Application issues:
1. If you checked the "play tracks from the jukebox block" setting then the tool needs to convert all your audio files to mono. That will require it to process every music file, even ones that are already in ogg format. But it shouldn't be failing to convert files to mono, **can you upload the original music files you used for your resourcepack so I can take a look?**
2. Are all of your disc images in .png format? The app only accepts .png images since that's the image format Minecraft expects. Image size and dimensions shouldn't matter (doesn't have to be exactly 16x16).

In-game issues:
All of your in-game issues sound like the resourcepack is not loading correctly for some reason. This may be related to your app issue 1. I saw you opened another issue #85, if you have any more questions about these in-game issues why don't you ask them on that issue.

Aternos should work fine. You might need to restart the server or run `/reload` after adding the datapack. I just generated a pack with 26 discs and uploaded it to an Aternos server and it worked. I used v1.5 of the app, with the "generate packs as zip" and "play tracks from the jukebox" settings enabled. I used the Aternos web UI to create a new server, added the datapack into my `world/datapacks` folder from the Files menu, and uploaded the resourcepack through the Options menu. After restarting the server, everything worked perfectly.

**Comment by GudanCraft** [comment]
Hello! Thanks for your quick reply!

- I do not know if my songs are stereo or mono, I just know they are .ogg, I will send you 2-3 examples of what i have in my folders so you can analyze them, if it's not a problem.
- All of the disc designs are .png, and I designed them myself in Paint 3D.

Well i do not know what to ask even, like, why doesn't the zipped RP load in my minecraft or something?
The datapack works properly on my aternos server, the issue is with not-loading resource packs.

I cannot attach my RP because it is too big, nor can i attach .ogg songs in github though.

Can you please a proper one for me if my app isn't okay?

**Comment by bradytheinventor** [comment]
You don't need to worry about whether the tracks are stereo or mono, just know that if you check the "play tracks from the jukebox block" setting then the tool will have to process every file whether it's already ogg or not.

I don't know why png images would not work, I can use any random png off my computer and the app handles it fine. Can you send me an example of a png that doesn't work?

If you have a Google Drive or Mediafire account, you could upload your resourcepack and the original files there and then link to it in a GitHub comment. Providing the problem resourcepack and original files would be very helpful for debugging because otherwise I'm just making guesses as I try to recreate the problem.

I don't understand your last question but if I can reproduce the issue you're seeing I'll try to fix it as soon as possible.

**Comment by GudanCraft** [comment]
Hello, I don't know how or why but I tried making a conpletely new one
where i placed all the settings to make the file zip itself instead of
myself and that it isn't mono and now everything works completely, thank
you for your help!

**Comment by bradytheinventor** [comment]
Great, glad that it's working!
