### ISSUE TITLE
music disc 11 plays when disc is inserted via redstone

### ISSUE THREAD

**Issue by C0smoPlays** [TeamTernate/infinite-music-discs#87]
I tried to make a mechanism that allowed for me to loop music boxes so music could play around my house but whenever the disc is inserted into the jukebox it just plays music disc 11, any possible fixes or workarounds? this was one of the main reasons I wanted to have the pack installed

forge 40.1.85

game 1.18.2

**Comment by bradytheinventor** [comment]
Unfortunately the jukebox redstone control only works in 1.19.4 and up, because jukebox redstone control wasn't added to the vanilla game until 1.19.4. You might be able to generate a pack for 1.19.4+ and use it in your 1.18.2 world, but I don't know if that will work and any bugs you encounter will not be investigated.
