### ISSUE TITLE
Latest file detected as Trojan by AVG, Avast and sandbox

### ISSUE THREAD

**Issue by NiraKiwi** [TeamTernate/infinite-music-discs#93]
The latest version of the program gets flagged as malicious by VirusTotal (see screenshot) and by my AVG antivirus.
I checked MD5 and it matches with the correct one.
![image](https://github.com/TeamTernate/infinite-music-discs/assets/78095551/7f9c37c0-be4a-476a-b2af-1f2c0f25c7d2)

**Comment by Pacstoliv** [comment]
Definitely having the same issue here. Hope it will be fixed soon.

**Comment by bradytheinventor** [comment]
Seems like the false positive rate with pyinstaller has gotten way worse recently. It's basically unusable now. I switched the app to use Nuitka and that helped, however I do still get 1 false positive from an AI enterprise security vendor. The correct solution is to rewrite the app in C++ instead of transpiling it but that takes time I don't have right now...

If you are unable to use v1.5 of the app I recommend you download the latest version and see if that fixes your problem. Or you can install Python, clone this repo, and run it directly.

**Comment by bradytheinventor** [comment]
v1.6.1 of the app which was just released has no false positive detections.
